---
# Disabled. Will be build by quay.io.

name: Create kroki container with plantuml stdlib

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - .github/dependabot.yml
      - 'LICENSE'
      - 'README.md'
      - '.idea'
      - 'kroki-container.iml'
  workflow_dispatch:

# Defines two custom environment variables for the workflow. These are used for the Container registry users, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: quay.io
  IMAGE_NAME: klenkes74/kroki

jobs:
  publish-quay:
    name: Create and Publish kroki Container
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ORG_USER }}
          password: ${{ secrets.QUAY_ORG_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
          outputs: type=image,name=target
